### ISSUE TITLE
hookModules is now expected to be defined in package.json

### ISSUE THREAD

**Issue by sbaechler** [GlassOfWhiskey/docker-gulp-tasks-4-liferay#1]
https://github.com/liferay/liferay-theme-tasks/blob/master/index.js#L21

**Comment by sbaechler** [comment]
The name of the deploy command has changed in Liferay 7.1, too. It is now `plugin:deploy`.

**Comment by sbaechler** [comment]
There is a new `deploy:war` task in 7.1 as well, which is the default task.

**Comment by GlassOfWhiskey** [comment]
Hi @sbaechler,
regarding the hookModules property, it can be actually defined:
 - Inside liferayThemeTasks.registerTasks block of the gulpfile.js
 - Inside the liferayTheme section of the package.json file

In case it's defined in both places, the one defined inside gulpfile.js will take precedence, overriding the default option

Regarding support for Liferay 7.1, please refer to https://github.com/GlassOfWhiskey/docker-gulp-tasks-4-liferay/issues/2

**Comment by sbaechler** [comment]
Oh, I missed the _.defaults function. Never mind.
