### ISSUE TITLE
support for Liferay 7.1

### ISSUE THREAD

**Issue by vernaillen** [GlassOfWhiskey/docker-gulp-tasks-4-liferay#2]
When I tried to use the module with Liferay 7.1 the watch task crashed because the task build:prep-css has been removed for Liferay 7.1 (liferay-theme-tasks:8.0.0-beta.1)

So I have tried to remove the build/prep-css task in docker_watch.js and then the module seems to work. I haven't tested this throughly though, but thought I could share this already:
https://github.com/triberay/docker-gulp-tasks-4-liferay/tree/7.1

**Comment by GlassOfWhiskey** [comment]
Hi @vernaillen, thank you for your contribution.
I was waiting for a new stable version of liferay-theme-tasks before starting a migration process. I hoped such version would be ready before the Liferay 7.1 release, but unfortunately things turned out differently.
Nevertheless, the plan is to release a version 2.0.0 of the plugin to be used with Liferay 7.1, while maintaining Liferay 7.0 compatibility with versions 1.x

**Comment by vernaillen** [comment]
I like the idea of a separate 2.0.0 version of the plugin for use with Liferay 7.1. 
Maybe a 2.0.0-beta.1 could be possible while we wait for the stable release of liferay-theme-tasks?

**Comment by jbalsas** [comment]
Hey @GlassOfWhiskey, @vernaillen, we're looking to [add this by default](https://github.com/liferay/liferay-themes-sdk/issues/72) to `liferay-theme-tasks`.

Is this something you'd be interested in contributing?

We'd like to have Docker `watch` and `deploy` support before we start our `8.0.0` release candidate process!

**Comment by GlassOfWhiskey** [comment]
Well, why not? I was planning to release version 2.0.0, but for a devdloper it's undoubtedly much better to find Docker support directly on Liferay packages. I will be happy to cobtribute and then to deprecate this repo if you want

**Comment by jbalsas** [comment]
Hey @GlassOfWhiskey, that's great to hear!

There are 2 repos where we will need to work:
- [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk)
- [liferay-plugin-node-tasks](https://github.com/jbalsas/liferay-plugin-node-tasks)

### liferay-themes-sdk

This is the main repo and where most related theme tools live. We will probably need to work around [liferay-theme-tasks](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/liferay-theme-tasks) to update the `deploy` and `watch` tools accordingly.

We will also need to at least update the dependency with the `liferay-plugin-node-tasks` in both the [liferay-theme-tasks](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/liferay-theme-tasks) module as well as the [generator-liferay-theme](https://github.com/liferay/liferay-themes-sdk/tree/master/packages/generator-liferay-theme) one.

### liferay-plugin-node-tasks

Contains common base functions to work with Liferay Plugins. This is where we might need to change some of the deployment strategies code. Whenever you see in the code a gulp task prefixed by `plugin:`, it lives here. For example:

```
gulp.task('deploy:gogo', function(cb) {
    let sequence = ['build', 'plugin:deploy-gogo', cb];
    ...
});
```

This repo also contains the [init_prompt](https://github.com/jbalsas/liferay-plugin-node-tasks/blob/master/lib/init_prompt.js) that contains all the questions regarding a theme setup. We recently added a [DEPLOYMENT_STRATEGY_OTHER](https://github.com/jbalsas/liferay-plugin-node-tasks/blob/master/lib/init_prompt.js#L99-L102) option to allow bypassing the only allowed mode before. That's probably where we should add a third, `DEPLOYMENT_STRATEGY_DOCKER` and ask the relevant questions needed for the configuration.

I'm going to be out travelling for a couple of days, but I'll be back next week :)

Please, let me know if you have any doubts or questions about this... looking forward to collaborating with you on this! ☺️

**Comment by GlassOfWhiskey** [comment]
Hi all, Docker support has been merged inside official [liferay-themes-sdk](https://github.com/liferay/liferay-themes-sdk) project, starting from version 8.0.0-rc.0
